ALTER TABLE "Mailbox"
ADD COLUMN "isPersonalTest" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Campaign"
ADD COLUMN "sendAnytime" BOOLEAN NOT NULL DEFAULT false;

ALTER TYPE "MessageStatus" ADD VALUE 'CANCELLED' AFTER 'QUEUED';
